const weatherTranslations = {
    "Sunny": "Cerah",
    "Partly cloudy": "Sebagian berawan",
    "Cloudy": "Berawan",
    "Overcast": "Mendung",
    "Mist": "Berkabut",
    "Patchy rain possible": "Hujan ringan mungkin",
    "Patchy snow possible": "Salju ringan mungkin",
    "Patchy sleet possible": "Hujan es ringan mungkin",
    "Patchy freezing drizzle possible": "Gerimis beku mungkin",
    "Thundery outbreaks possible": "Mungkin ada badai petir",
    "Blowing snow": "Badai salju",
    "Blizzard": "Badai salju lebat",
    "Fog": "Kabut",
    "Freezing fog": "Kabut beku",
    "Patchy light drizzle": "Gerimis ringan",
    "Light drizzle": "Gerimis",
    "Freezing drizzle": "Gerimis beku",
    "Heavy freezing drizzle": "Gerimis beku lebat",
    "Patchy light rain": "Hujan ringan mungkin",
    "Light rain": "Hujan ringan",
    "Moderate rain at times": "Hujan sedang sesekali",
    "Moderate rain": "Hujan sedang",
    "Heavy rain at times": "Hujan lebat sesekali",
    "Heavy rain": "Hujan lebat",
    "Light freezing rain": "Hujan beku ringan",
    "Moderate or heavy freezing rain": "Hujan beku sedang atau lebat",
    "Light sleet": "Hujan es ringan",
    "Moderate or heavy sleet": "Hujan es sedang atau lebat",
    "Patchy light snow": "Salju ringan mungkin",
    "Light snow": "Salju ringan",
    "Patchy moderate snow": "Salju sedang mungkin",
    "Moderate snow": "Salju sedang",
    "Patchy heavy snow": "Salju lebat mungkin",
    "Heavy snow": "Salju lebat",
    "Ice pellets": "Bola es",
    "Light rain shower": "Hujan ringan",
    "Moderate or heavy rain shower": "Hujan sedang atau lebat",
    "Torrential rain shower": "Hujan deras",
    "Light sleet showers": "Hujan es ringan",
    "Moderate or heavy sleet showers": "Hujan es sedang atau lebat",
    "Light snow showers": "Hujan salju ringan",
    "Moderate or heavy snow showers": "Hujan salju sedang atau lebat",
    "Light showers of ice pellets": "Hujan bola es ringan",
    "Moderate or heavy showers of ice pellets": "Hujan bola es sedang atau lebat",
    "Patchy light rain with thunder": "Hujan ringan dengan petir",
    "Moderate or heavy rain with thunder": "Hujan sedang atau lebat dengan petir",
    "Patchy light snow with thunder": "Salju ringan dengan petir",
    "Moderate or heavy snow with thunder": "Salju sedang atau lebat dengan petir"
};